const logger = require('./logger');

/**
 * Generates an LLM prompt for code review analysis with cleaned diffs
 * @param {Object} prData - Pull request metadata
 * @param {Array} cleanedDiff - Array of cleaned file diffs
 * @returns {string} - Formatted LLM prompt
 */
function generateLLMPrompt(prData, cleanedDiff) {
  try {
    if (!cleanedDiff || cleanedDiff.length === 0) {
      logger.warn('No cleaned diff available for prompt generation');
      return null;
    }

    // Build the prompt structure
    let prompt = `# Code Review Request\n\n`;
    
    // PR Metadata
    prompt += `## Pull Request Information\n`;
    prompt += `- **Repository:** ${prData.repository}\n`;
    prompt += `- **PR Number:** #${prData.pullRequestNumber}\n`;
    prompt += `- **Title:** ${prData.title}\n`;
    prompt += `- **Author:** ${prData.author}\n`;
    prompt += `- **Action:** ${prData.action}\n\n`;

    // Instructions for LLM
    prompt += `## Review Instructions\n`;
    prompt += `Please analyze the following code changes and provide a comprehensive code review focusing on:\n`;
    prompt += `1. **Code Quality**: Best practices, readability, maintainability\n`;
    prompt += `2. **Security**: Potential vulnerabilities, security best practices\n`;
    prompt += `3. **Performance**: Optimization opportunities, efficiency concerns\n`;
    prompt += `4. **Bugs**: Potential errors, edge cases, logic issues\n`;
    prompt += `5. **Documentation**: Missing comments, unclear code\n\n`;

    // Code Changes
    prompt += `## Code Changes\n\n`;
    
    for (let i = 0; i < cleanedDiff.length; i++) {
      const file = cleanedDiff[i];
      
      prompt += `### File ${i + 1}: \`${file.filename}\`\n`;
      prompt += `**Language:** ${file.language}\n`;
      if (file.status) {
        prompt += `**Status:** ${file.status}\n`;
      }
      if (file.additions !== undefined && file.deletions !== undefined) {
        prompt += `**Changes:** +${file.additions} / -${file.deletions} lines\n`;
      }
      prompt += `\n\`\`\`${file.language}\n`;
      prompt += `${file.changes}\n`;
      prompt += `\`\`\`\n\n`;
    }

    // Analysis Request
    prompt += `## Analysis Request\n\n`;
    prompt += `Please provide:\n`;
    prompt += `1. **Summary**: Brief overview of the changes\n`;
    prompt += `2. **Issues Found**: List any bugs, security concerns, or code quality issues\n`;
    prompt += `3. **Suggestions**: Recommendations for improvement\n`;
    prompt += `4. **Positive Feedback**: What was done well\n`;
    prompt += `5. **Priority**: Mark critical issues that should be addressed before merging\n\n`;

    prompt += `---\n`;
    prompt += `*Generated by GitGuard AI - Automated Code Review System*\n`;

    return prompt;

  } catch (error) {
    logger.error('Error generating LLM prompt', {
      error: error.message,
      stack: error.stack
    });
    throw error;
  }
}

/**
 * Generates a compact LLM prompt (token-efficient version)
 * @param {Object} prData - Pull request metadata
 * @param {Array} cleanedDiff - Array of cleaned file diffs
 * @returns {string} - Compact formatted LLM prompt
 */
function generateCompactLLMPrompt(prData, cleanedDiff) {
  try {
    if (!cleanedDiff || cleanedDiff.length === 0) {
      return null;
    }

    // Compact format for token efficiency
    let prompt = `Review PR #${prData.pullRequestNumber} in ${prData.repository} by ${prData.author}.\n`;
    prompt += `Title: ${prData.title}\n\n`;
    prompt += `Analyze for: bugs, security issues, performance, code quality.\n\n`;

    for (const file of cleanedDiff) {
      prompt += `File: ${file.filename} (${file.language})\n`;
      prompt += `\`\`\`${file.language}\n${file.changes}\n\`\`\`\n\n`;
    }

    prompt += `Provide: issues, suggestions, and priority levels.`;

    return prompt;

  } catch (error) {
    logger.error('Error generating compact LLM prompt', {
      error: error.message
    });
    throw error;
  }
}

/**
 * Generates structured prompt data for API consumption
 * @param {Object} prData - Pull request metadata
 * @param {Array} cleanedDiff - Array of cleaned file diffs
 * @param {string} format - 'full' or 'compact'
 * @returns {Object} - Structured prompt data
 */
function generateStructuredPrompt(prData, cleanedDiff, format = 'full') {
  try {
    const promptText = format === 'compact' 
      ? generateCompactLLMPrompt(prData, cleanedDiff)
      : generateLLMPrompt(prData, cleanedDiff);

    if (!promptText) {
      return null;
    }

    // Calculate token estimate (rough: 1 token ≈ 4 characters)
    const estimatedTokens = Math.ceil(promptText.length / 4);

    return {
      prompt: promptText,
      format: format,
      estimatedTokens: estimatedTokens,
      fileCount: cleanedDiff.length,
      totalChanges: cleanedDiff.reduce((sum, file) => sum + (file.changes?.length || 0), 0),
      generatedAt: new Date().toISOString()
    };

  } catch (error) {
    logger.error('Error generating structured prompt', {
      error: error.message
    });
    throw error;
  }
}

module.exports = {
  generateLLMPrompt,
  generateCompactLLMPrompt,
  generateStructuredPrompt
};
